# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/const1.xdc

# Block Designs: bd/design_2/design_2.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2 || ORIG_REF_NAME==design_2} -quiet] -quiet

# IP: bd/design_2/ip/design_2_print_reg_0_0_1/design_2_print_reg_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_print_reg_0_0 || ORIG_REF_NAME==design_2_print_reg_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_print_data_reg_0_0_1/design_2_print_data_reg_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_print_data_reg_0_0 || ORIG_REF_NAME==design_2_print_data_reg_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_fsm_intr_0_0_1/design_2_fsm_intr_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_fsm_intr_0_0 || ORIG_REF_NAME==design_2_fsm_intr_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_clk_divider_UART_0_0_1/design_2_clk_divider_UART_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_clk_divider_UART_0_0 || ORIG_REF_NAME==design_2_clk_divider_UART_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_clk_divider_0_0_1/design_2_clk_divider_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_clk_divider_0_0 || ORIG_REF_NAME==design_2_clk_divider_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_LUT_0_0_1/design_2_LUT_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_LUT_0_0 || ORIG_REF_NAME==design_2_LUT_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_Counter_27_0_0_1/design_2_Counter_27_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_Counter_27_0_0 || ORIG_REF_NAME==design_2_Counter_27_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_Comp_27_0_0_1/design_2_Comp_27_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_Comp_27_0_0 || ORIG_REF_NAME==design_2_Comp_27_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_CTRL_0_0_1/design_2_CTRL_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_CTRL_0_0 || ORIG_REF_NAME==design_2_CTRL_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_Addr_ctrl_0_0_1/design_2_Addr_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_Addr_ctrl_0_0 || ORIG_REF_NAME==design_2_Addr_ctrl_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_Addr_Counter_0_0_1/design_2_Addr_Counter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_Addr_Counter_0_0 || ORIG_REF_NAME==design_2_Addr_Counter_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_tx_mod_0_0_1/design_2_tx_mod_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_tx_mod_0_0 || ORIG_REF_NAME==design_2_tx_mod_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_Gripper_ctrl_0_0_1/design_2_Gripper_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_Gripper_ctrl_0_0 || ORIG_REF_NAME==design_2_Gripper_ctrl_0_0} -quiet] -quiet

# XDC: /home/daniel/Documents/SDU/1.Semester_msc/Embedded/miniProject/EmbeddedSystems/IMU_SPI_UART/project_imu_spi_uart/project_imu_spi_uart.gen/sources_1/bd/design_2/design_2_ooc.xdc
