#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Thu Dec 30 15:33:04 CET 2021
# SW Build 3247384 on Thu Jun 10 19:36:07 MDT 2021
#
# IP Build 3246043 on Fri Jun 11 00:30:35 MDT 2021
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto 2dc18f4cf8dd4f06a3f1105f0e9e1ff1 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip -L xpm --snapshot Addr_Counter_behav xil_defaultlib.Addr_Counter -log elaborate.log"
xelab -wto 2dc18f4cf8dd4f06a3f1105f0e9e1ff1 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip -L xpm --snapshot Addr_Counter_behav xil_defaultlib.Addr_Counter -log elaborate.log

